name: Create Azure Key Vault Secrets
on:
  workflow_dispatch:
    inputs:
      vault-name:
        description: 'Please select your vaults'
        required: true
        type: choice
        options:
         - hk-kunlawit-keyvault
         - sg-kunlawit-keyvault
         - both
      secret:
        description: 'Please enter your secret'
        required: true
      value:
        description: 'Please enter your value'
        required: true
jobs:
  create_secrets:
    runs-on: self-hosted

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.SUBSCRIPTION }}

      - name: Create secrets in Azure Key Vault
        run: |
          if [[ "${{ inputs.vault-name }}" == "hk-kunlawit-keyvault" ]]; then
            az keyvault secret set --vault-name hk-kunlawit-keyvault --name ${{ inputs.secret }} --value ${{ inputs.value }}
          fi
          if [[ "${{ inputs.vault-name }}" == "sg-kunlawit-keyvault" ]]; then
            az keyvault secret set --vault-name sg-kunlawit-keyvault --name ${{ inputs.secret }} --value ${{ inputs.value }}
          fi
          if [[ "${{ inputs.vault-name }}" == "both" ]]; then
            az keyvault secret set --vault-name hk-kunlawit-keyvault --name ${{ inputs.secret }} --value ${{ inputs.value }}
            az keyvault secret set --vault-name sg-kunlawit-keyvault --name ${{ inputs.secret }} --value ${{ inputs.value }}
          fi
        
          
