name: Create Azure Key Vault Secrets

on:
  push:
    branches:
      - master

jobs:
  create_secrets:
    runs-on: self-hosted

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.SUBSCRIPTION }}

      - name: Create secrets in kunlawt24keyvault
        run: |
          az keyvault secret set --vault-name kunlawt24keyvault --name "test-secret" --value "test-secret-value"

      - name: Create secrets in kunlawt24keyvault02
        run: |
          az keyvault secret set --vault-name kunlawt24keyvault02 --name "test-secret" --value "test-secret-value"
