name: Create Azure Key Vault Secrets
on:
  workflow_dispatch:
    inputs:
      vault-name:
        description: 'Please select your vaults'
        required: true
        type: choice
        options:
         - kunlawt24keyvault
         - kunlawt24keyvault02
         - both
      secret:
        description: 'Please enter your secret'
        required: true
      value:
        description: 'Please enter your secret'
        required: true
jobs:
  create_secrets:
    runs-on: self-hosted

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.SUBSCRIPTION }}

      - name: Create secrets in Azure Key Vault
        run: |
          az keyvault secret set --vault-name ${{ inputs.vault-name }} --name ${{ inputs.secret }} --value ${{ inputs.value }}
