name: AzureKeyVault_InputSecrets

on:
  push:
    branches:
      - master

jobs:
  create_secrets:
    runs-on: self-hosted

    inputs:
      secret_name:
        description: 'The name of the secret'
        required: true
      value:
        description: 'The value of the secret'
        required: true

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.SUBSCRIPTION }}

      - name: Create secrets in Azure Key Vault
        run: |
          az keyvault secret set --vault-name kunlawt24keyvault --name ${{ github.event.inputs.secret_name }} --value ${{ github.event.inputs.value }}
          az keyvault secret set --vault-name kunlawt24keyvault02 --name ${{ github.event.inputs.secret_name }} --value ${{ github.event.inputs.value }}
