name: build_and_deploy
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image:  azure-vote-front
          folder: azure-vote
          branch: master
          tag: ${{ github.sha }}
