name: Redeploy nginx after changes in deployment.yaml
on: [workflow_dispatch]

jobs:
  redeploy-nginx:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Redeploy nginx
        run: |
          kubectl apply -f azure-voting-app-redis/deployment.yaml
