name: deploy
on: [workflow_dispatch]
jobs:
  redeploy-nginx:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Redeploy nginx
        run: |
          kubectl apply -f deployment.yaml
