name: deploy
on: [workflow_dispatch]
jobs:
  test-deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to local cluster
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
             azure-vote-all-in-one-redis.yaml
          images: '${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}'
          pull-images: false
