name: deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          kubectl apply -f azure-vote-all-in-one-redis.yaml
