name: deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: test-deploy
        id: test-deploy-local
        uses: actions/checkout@v3
        with:
          namespace: 'default'
          manifests: |
             azure-vote-all-in-one-redis.yaml
          images: '${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}'
          pull-images: false

